### ISSUE TITLE
js class

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storechild#2]
Do we need to add this in the child theme? If it's required, wouldn't it be better in Storefront Core?

**Comment by mendezcode** [comment]
Not all themes may use the class, so I think adding the function on Storefront and enqueuing optionally would work better. Something like `storefront_js_detection()` would be good. What do you think?

**Comment by jameskoster** [comment]
As discussed on Slack, we probably don't need this. Can be removed :)
